name: Build
on: [push]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_linux
          path: |
            release
            !release/linux-unpacked/
            !release/linux-armv7l-unpacked/
            !release/linux-arm64-unpacked/
            !release/builder-debug.yml

  build_on_mac:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_macos
          path: |
            release
            !release/mac/
            !release/builder-debug.yml

  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_win
          path: |
            release
            !release/builder-debug.yml
            !release/builder-effective-config.yaml
            !release/win-unpacked/
            !release/win-ia32-unpacked/